load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "scheduler",
    srcs = [
        "interface.go",
        "manager.go",
        "register.go",
        "scheduler.go",
    ],
    importpath = "github.com/pingcap/tidb/disttask/framework/scheduler",
    visibility = ["//visibility:public"],
    deps = [
        "//br/pkg/lightning/common",
        "//br/pkg/lightning/log",
        "//config",
        "//disttask/framework/dispatcher",
        "//disttask/framework/handle",
        "//disttask/framework/proto",
        "//disttask/framework/scheduler/execute",
        "//disttask/framework/storage",
        "//domain/infosync",
        "//metrics",
        "//parser/terror",
        "//resourcemanager/pool/spool",
        "//resourcemanager/util",
        "//util",
        "//util/backoff",
        "//util/dbterror",
        "//util/gctuner",
        "//util/logutil",
        "//util/memory",
        "@com_github_pingcap_errors//:errors",
        "@com_github_pingcap_failpoint//:failpoint",
        "@org_uber_go_zap//:zap",
    ],
)

go_test(
    name = "scheduler_test",
    timeout = "short",
    srcs = [
        "manager_test.go",
        "register_test.go",
        "scheduler_test.go",
        "scheduler_testkit_test.go",
    ],
    embed = [":scheduler"],
    flaky = True,
    race = "on",
    shard_count = 9,
    deps = [
        "//disttask/framework/mock",
        "//disttask/framework/mock/execute",
        "//disttask/framework/proto",
        "//disttask/framework/storage",
        "//disttask/framework/testutil",
        "//kv",
        "//resourcemanager/pool/spool",
        "//resourcemanager/util",
        "//testkit",
        "//util/logutil",
        "@com_github_ngaut_pools//:pools",
        "@com_github_pingcap_errors//:errors",
        "@com_github_pingcap_failpoint//:failpoint",
        "@com_github_stretchr_testify//require",
        "@com_github_tikv_client_go_v2//util",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_uber_go_mock//gomock",
    ],
)
