load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "audit",
    srcs = [
        "entry.go",
        "filter.go",
        "logger.go",
        "manager.go",
        "register.go",
        "util.go",
    ],
    importpath = "github.com/pingcap/tidb/extension/serverless/audit",
    visibility = ["//visibility:public"],
    deps = [
        "//config",
        "//extension",
        "//keyspace",
        "//kv",
        "//metrics",
        "//parser/ast",
        "//parser/auth",
        "//parser/mysql",
        "//parser/terror",
        "//sessionctx/stmtctx",
        "//sessionctx/variable",
        "//types",
        "//util/chunk",
        "//util/encrypt",
        "//util/logutil",
        "//util/sqlexec",
        "//util/stringutil",
        "//util/table-filter",
        "@com_github_google_uuid//:uuid",
        "@com_github_ngaut_pools//:pools",
        "@com_github_pingcap_errors//:errors",
        "@com_github_pingcap_log//:log",
        "@in_gopkg_natefinch_lumberjack_v2//:lumberjack_v2",
        "@io_etcd_go_etcd_api_v3//mvccpb",
        "@io_etcd_go_etcd_client_v3//:client",
        "@org_uber_go_atomic//:atomic",
        "@org_uber_go_zap//:zap",
        "@org_uber_go_zap//zapcore",
    ],
)

go_test(
    name = "audit_test",
    timeout = "short",
    srcs = [
        "entry_test.go",
        "filter_test.go",
        "function_test.go",
        "sysvar_test.go",
    ],
    embed = [":audit"],
    flaky = True,
    shard_count = 20,
    deps = [
        "//config",
        "//errno",
        "//parser",
        "//parser/auth",
        "//server",
        "//sessionctx/stmtctx",
        "//testkit",
        "//util/sem",
        "@com_github_pingcap_errors//:errors",
        "@com_github_stretchr_testify//require",
        "@org_uber_go_zap//:zap",
    ],
)
