name: Bump TiDB Version to aws-shared-provider

# This workflow will create a new pull request to bump the TiDB version to aws-shared-provider.
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to bump, like commit sha"
        required: true
      deploy_env:
        description: "Deploy Environment"
        required: true
        default: "dev"
        type: choice
        # please not change these options, they are used in the subsequent job:
        # 1. https://github.com/tidbcloud/aws-shared-provider/blob/main/.github/workflows/bump-tidb-version.yaml
        options:
          - dev
          - staging
          - prod

jobs:
  bump-tidb-version:
    name: bump tidb version
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Invoke workflow in aws-shared-provider repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Bump the tidb version
          repo: tidbcloud/aws-shared-provider
          ref: refs/heads/master
          token: ${{ secrets.GIT_ACTION_BOT }}
          inputs: '{ "version": "${{ github.event.inputs.version }}", "env": "${{ github.event.inputs.deploy_env }}", "action_url": "${{github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}", "author": "${{ github.actor }}" }'

