name: TiDB-CI

on:
  push:
    branches: ["release-7.1-keyspace"]
  pull_request:
    branches: ["release-7.1-keyspace"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tidb-cse-check:
    runs-on: x64
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_ACTION_BOT }}
      GOPRIVATE: github.com/tidbcloud
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache-dependency-path: ./go.sum
        env:
          GOPRIVATE: "github.com/tidbcloud,github.com/pingcap/dbaas"

      - name: setup bazel
        uses: jwlawson/actions-setup-bazel@v1.9.0
        with:
          bazel-version: '5.4.0'

      - name: check
        shell: bash
        run: |
          make check

  tidb-cse-build:
    runs-on: self-hosted
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_ACTION_BOT }}
      GOPRIVATE: github.com/tidbcloud
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache-dependency-path: ./go.sum
        env:
          GOPRIVATE: "github.com/tidbcloud,github.com/pingcap/dbaas"

      - name: build
        shell: bash
        run: |
          make
