name: TiDB-UT

on:
  pull_request:
    branches: [ "release-7.1-keyspace" ]
    types: [ opened, synchronize, reopened, labeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  TiDB-Test-Part1:
    runs-on: x64
    if: contains(github.event.pull_request.labels.*.name, 'run-ut')
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_ACTION_BOT }}
      GOPRIVATE: github.com/tidbcloud
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum
        env:
          GOPRIVATE: "github.com/tidbcloud,github.com/pingcap/dbaas"

      - name: make test_part_1
        shell: bash
        run: |
          make test_part_1

  TiDB-Test-Part2:
    runs-on: x64
    if: contains(github.event.pull_request.labels.*.name, 'run-ut')
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_ACTION_BOT }}
      GOPRIVATE: github.com/tidbcloud
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum
        env:
          GOPRIVATE: "github.com/tidbcloud,github.com/pingcap/dbaas"

      - name: make test_part_2
        shell: bash
        run: |
          make test_part_2

  TiDB-Unit-Test:
    runs-on: x64
    if: contains(github.event.pull_request.labels.*.name, 'run-ut')
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        worker_id: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 ]
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum
        env:
          GOPRIVATE: "github.com/tidbcloud,github.com/pingcap/dbaas"

      - name: make ut-test
        env:
          WORKER_ID: ${{ matrix.worker_id }}
          WORKER_COUNT: 16
          TZ: Asia/Shanghai
        run: |
          make ci-test-job JOB_COUNT=$(($WORKER_COUNT)) JOB_INDEX=$WORKER_ID
